# Generated by Django 4.2.6 on 2023-10-29 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=255)),
                ('owner', models.EmailField(max_length=254)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('private_key', models.FileField(upload_to='uploads/private_keys')),
                ('certificate', models.FileField(upload_to='uploads/certs')),
            ],
        ),
        migrations.CreateModel(
            name='CertificateRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_key', models.FileField(blank=True, null=True, upload_to='renewal_private_keys/')),
                ('certificate_request', models.FileField(blank=True, null=True, upload_to='renewal_csr_files/')),
                ('renewed_certificate', models.FileField(blank=True, null=True, upload_to='renewed_certificates/')),
                ('request_complete', models.BooleanField(default=False)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certs.certificate')),
            ],
        ),
    ]
