# Generated by Django 4.2.6 on 2024-03-29 11:38

import certs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_alter_certificaterenewal_certificate_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='notes',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(upload_to=certs.models.custom_cert_name),
        ),
    ]
