# Generated by Django 4.2.6 on 2023-10-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterenewal',
            name='certificate_request',
            field=models.FileField(blank=True, null=True, upload_to='uploads/renewal_csr_files/'),
        ),
        migrations.AlterField(
            model_name='certificaterenewal',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='uploads/renewal_private_keys/'),
        ),
        migrations.AlterField(
            model_name='certificaterenewal',
            name='renewed_certificate',
            field=models.FileField(blank=True, null=True, upload_to='uploads/renewed_certificates/'),
        ),
    ]
