# Generated by Django 4.2.15 on 2025-01-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0004_certificate_archived_alter_certificate_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='archived',
        ),
        migrations.AddField(
            model_name='certificate',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='expiry_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='owner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_keys/'),
        ),
    ]
