# Generated by Django 5.1.5 on 2025-01-16 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
